# Generated by Django 5.1 on 2026-01-25 03:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="import_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="import_source",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reference_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
