# Generated by Django 5.1 on 2026-01-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0002_transaction_import_date_transaction_import_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="monthly_budget",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monthly budget amount for this category",
                max_digits=10,
            ),
        ),
    ]
