# Generated by Django 5.1 on 2026-01-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0003_category_monthly_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="classification",
            field=models.CharField(
                choices=[("spend", "Spend"), ("income", "Income")],
                default="spend",
                help_text="Whether this category is for spending or income",
                max_length=10,
            ),
        ),
    ]
