# Generated by Django 5.1 on 2026-01-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_transaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Ticker symbol or identifier', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full name of the investment', max_length=200)),
                ('investment_type', models.CharField(choices=[('stock', 'Stock'), ('bond', 'Bond'), ('etf', 'ETF'), ('crypto', 'Cryptocurrency'), ('mutual_fund', 'Mutual Fund')], default='stock', help_text='Type of investment', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Number of shares/units owned', max_digits=15)),
                ('purchase_price', models.DecimalField(decimal_places=4, help_text='Average purchase price per share/unit', max_digits=15)),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, help_text='Current market price per share/unit (optional, can be updated manually)', max_digits=15, null=True)),
                ('purchase_date', models.DateField(help_text='Date of initial purchase')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the investment', null=True)),
            ],
        ),
    ]
