# Generated by Django 5.1 on 2026-01-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_heritage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetirementAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or nickname for this retirement account', max_length=200)),
                ('account_type', models.CharField(choices=[('traditional_401k', 'Traditional 401(k)'), ('roth_401k', 'Roth 401(k)'), ('traditional_ira', 'Traditional IRA'), ('roth_ira', 'Roth IRA'), ('sep_ira', 'SEP IRA'), ('simple_ira', 'SIMPLE IRA'), ('pension', 'Pension'), ('annuity', 'Annuity'), ('other', 'Other')], default='traditional_401k', help_text='Type of retirement account', max_length=20)),
                ('provider', models.CharField(help_text='Financial institution or provider (e.g., Fidelity, Vanguard)', max_length=100)),
                ('account_number', models.CharField(blank=True, help_text='Account number (last 4 digits for security)', max_length=50, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='Current account balance', max_digits=15)),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=0, help_text='Monthly contribution amount', max_digits=10)),
                ('employer_match_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Employer match percentage (e.g., 0.50 for 50%)', max_digits=5)),
                ('employer_match_limit', models.DecimalField(decimal_places=2, default=0, help_text='Maximum employer match amount per year', max_digits=10)),
                ('risk_level', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive'), ('very_aggressive', 'Very Aggressive')], default='moderate', help_text='Risk level of the investment portfolio', max_length=20)),
                ('target_retirement_age', models.PositiveIntegerField(default=65, help_text='Target retirement age')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the account', null=True)),
            ],
        ),
    ]
