# Generated by Django 5.1 on 2026-02-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_assign_default_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Make user fields required
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='heritage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heritages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='retirementaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retirement_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investment',
            name='symbol',
            field=models.CharField(help_text='Ticker symbol or identifier', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together={('user', 'symbol')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'classification'], name='budget_cate_user_id_a0256c_idx'),
        ),
        migrations.AddIndex(
            model_name='heritage',
            index=models.Index(fields=['user', 'heritage_type'], name='budget_heri_user_id_3fcafe_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'investment_type'], name='budget_inve_user_id_36b772_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'purchase_date'], name='budget_inve_user_id_05ca1f_idx'),
        ),
        migrations.AddIndex(
            model_name='retirementaccount',
            index=models.Index(fields=['user', 'account_type'], name='budget_reti_user_id_598f47_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='budget_tran_user_id_fcff6a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category'], name='budget_tran_user_id_7b11f3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-date'], name='budget_tran_user_id_ecc502_idx'),
        ),
    ]
