[pytest]
DJANGO_SETTINGS_MODULE = personal_finance_management.settings
python_files = tests.py test_*.py *_tests.py
addopts = -v --tb=short

[coverage:run]
source =
    budget
    core
    wealth
omit =
    */migrations/*
    */tests/*
