# Generated by Django 5.1 on 2026-02-02 consolidated

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "classification",
                    models.CharField(
                        choices=[("spend", "Spend"), ("income", "Income")],
                        default="spend",
                        help_text="Whether this category is for spending or income",
                        max_length=10,
                    ),
                ),
                (
                    "monthly_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly budget amount for this category",
                        max_digits=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Heritage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name or description of the property", max_length=200
                    ),
                ),
                (
                    "heritage_type",
                    models.CharField(
                        choices=[
                            ("land", "Land"),
                            ("house", "House"),
                            ("apartment", "Apartment"),
                            ("commercial", "Commercial Property"),
                            ("office", "Office"),
                            ("warehouse", "Warehouse"),
                            ("other", "Other"),
                        ],
                        default="house",
                        help_text="Type of heritage/property",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(help_text="Full address of the property")),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Area in square meters or appropriate unit",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "area_unit",
                    models.CharField(
                        default="sq_m",
                        help_text="Unit for area measurement (sq_m, acres, hectares, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Purchase price of the property",
                        max_digits=15,
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current market value (optional, can be updated manually)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("purchase_date", models.DateField(help_text="Date of purchase")),
                (
                    "monthly_rental_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly rental income if applicable",
                        max_digits=10,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the property",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heritages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Ticker symbol or identifier", max_length=20
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the investment", max_length=200
                    ),
                ),
                (
                    "investment_type",
                    models.CharField(
                        choices=[
                            ("stock", "Stock"),
                            ("bond", "Bond"),
                            ("etf", "ETF"),
                            ("crypto", "Cryptocurrency"),
                            ("mutual_fund", "Mutual Fund"),
                            ("fixed_income", "Fixed Income"),
                        ],
                        default="stock",
                        help_text="Type of investment",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Number of shares/units owned",
                        max_digits=15,
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Average purchase price per share/unit",
                        max_digits=15,
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Current market price per share/unit (optional, can be updated manually)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(help_text="Date of initial purchase"),
                ),
                (
                    "principal_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Principal amount for fixed income investments",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual interest rate (e.g., 8.00 for 8%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "compounding_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("annual", "Annual"),
                            ("semi_annual", "Semi-Annual"),
                            ("quarterly", "Quarterly"),
                            ("monthly", "Monthly"),
                        ],
                        help_text="How often interest is compounded",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "term_years",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Investment term in years",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the investment",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RetirementAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name or nickname for this retirement account",
                        max_length=200,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("traditional_401k", "Traditional 401(k)"),
                            ("roth_401k", "Roth 401(k)"),
                            ("traditional_ira", "Traditional IRA"),
                            ("roth_ira", "Roth IRA"),
                            ("sep_ira", "SEP IRA"),
                            ("simple_ira", "SIMPLE IRA"),
                            ("pension", "Pension"),
                            ("annuity", "Annuity"),
                            ("other", "Other"),
                        ],
                        default="traditional_401k",
                        help_text="Type of retirement account",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="Financial institution or provider (e.g., Fidelity, Vanguard)",
                        max_length=100,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        help_text="Account number (last 4 digits for security)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current account balance",
                        max_digits=15,
                    ),
                ),
                (
                    "monthly_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly contribution amount",
                        max_digits=10,
                    ),
                ),
                (
                    "employer_match_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Employer match percentage (e.g., 0.50 for 50%)",
                        max_digits=5,
                    ),
                ),
                (
                    "employer_match_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Maximum employer match amount per year",
                        max_digits=10,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("conservative", "Conservative"),
                            ("moderate", "Moderate"),
                            ("aggressive", "Aggressive"),
                            ("very_aggressive", "Very Aggressive"),
                        ],
                        default="moderate",
                        help_text="Risk level of the investment portfolio",
                        max_length=20,
                    ),
                ),
                (
                    "target_retirement_age",
                    models.PositiveIntegerField(
                        default=65, help_text="Target retirement age"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the account",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retirement_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("account", "Account"),
                        ],
                        default="account",
                        help_text="Type of transaction: credit card or account",
                        max_length=20,
                    ),
                ),
                (
                    "import_source",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("import_date", models.DateTimeField(auto_now_add=True)),
                (
                    "reference_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["user", "classification"], name="budget_cate_user_id_a0256c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("user", "name")},
        ),
        migrations.AddIndex(
            model_name="heritage",
            index=models.Index(
                fields=["user", "heritage_type"], name="budget_heri_user_id_3fcafe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investment",
            index=models.Index(
                fields=["user", "investment_type"],
                name="budget_inve_user_id_36b772_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="investment",
            index=models.Index(
                fields=["user", "purchase_date"], name="budget_inve_user_id_05ca1f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="investment",
            unique_together={("user", "symbol")},
        ),
        migrations.AddIndex(
            model_name="retirementaccount",
            index=models.Index(
                fields=["user", "account_type"], name="budget_reti_user_id_598f47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "date"], name="budget_tran_user_id_fcff6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "category"], name="budget_tran_user_id_7b11f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "-date"], name="budget_tran_user_id_ecc502_idx"
            ),
        ),
    ]
