# Generated by Django 5.1 on 2026-02-04 04:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0003_add_reclassification_deletion_rules"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="categorydeletionrule",
            new_name="budget_cate_user_id_24bf21_idx",
            old_name="budget_cate_user_id_8f4a5c_idx",
        ),
        migrations.RenameIndex(
            model_name="reclassificationrule",
            new_name="budget_recl_user_id_4b8493_idx",
            old_name="budget_recl_user_id_e9b8c5_idx",
        ),
    ]
