# Generated by Django 5.1 on 2026-01-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_category_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('account', 'Account')], default='account', help_text='Type of transaction: credit card or account', max_length=20),
        ),
    ]
