# Generated by Django 5.1 on 2026-03-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0006_reclassificationrule_dynamic_conditions"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="transaction",
            new_name="budget_tran_user_id_c946cc_idx",
            old_name="budget_tran_user_id_e7fa3b_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="budget_tran_referen_8579b5_idx",
            old_name="budget_tran_referen_8e6f9a_idx",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reference_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
