# Generated by Django 5.1 on 2026-01-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_investment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heritage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or description of the property', max_length=200)),
                ('heritage_type', models.CharField(choices=[('land', 'Land'), ('house', 'House'), ('apartment', 'Apartment'), ('commercial', 'Commercial Property'), ('office', 'Office'), ('warehouse', 'Warehouse'), ('other', 'Other')], default='house', help_text='Type of heritage/property', max_length=20)),
                ('address', models.TextField(help_text='Full address of the property')),
                ('area', models.DecimalField(blank=True, decimal_places=2, help_text='Area in square meters or appropriate unit', max_digits=10, null=True)),
                ('area_unit', models.CharField(default='sq_m', help_text='Unit for area measurement (sq_m, acres, hectares, etc.)', max_length=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Purchase price of the property', max_digits=15)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, help_text='Current market value (optional, can be updated manually)', max_digits=15, null=True)),
                ('purchase_date', models.DateField(help_text='Date of purchase')),
                ('monthly_rental_income', models.DecimalField(decimal_places=2, default=0, help_text='Monthly rental income if applicable', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the property', null=True)),
            ],
        ),
    ]
