# Generated by Django 5.1 on 2026-01-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_retirementaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritage',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Purchase price of the property', max_digits=15),
        ),
    ]
