# Generated by Django 5.1 on 2026-01-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_alter_heritage_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='compounding_frequency',
            field=models.CharField(blank=True, choices=[('annual', 'Annual'), ('semi_annual', 'Semi-Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly')], help_text='How often interest is compounded', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual interest rate (e.g., 8.00 for 8%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='principal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Principal amount for fixed income investments', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='term_years',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Investment term in years', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('bond', 'Bond'), ('etf', 'ETF'), ('crypto', 'Cryptocurrency'), ('mutual_fund', 'Mutual Fund'), ('fixed_income', 'Fixed Income')], default='stock', help_text='Type of investment', max_length=20),
        ),
    ]
